config/routes.rb
VerkkoCrm::Application.routes.draw do
  scope 'api' do
    resources :prospects
  end

  get "users/new"

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',        to: 'users#new'
  match '/login',         to: 'sessions#new'
  match '/logout',        to: 'sessions#destroy'
 
  match '/prospects',     to: 'pages#prospects'
  match '/agents',        to: 'pages#agents'
  match '/backoffice',    to: 'pages#backoffice'
  match '/config_user',   to: 'pages#config_user'
  match '/home',          to: 'pages#home'

  root                    to: 'pages#home'

end

app/models/prospect.rb
# == Schema Information
#
# Table name: prospects
#
#  id                :integer          not null, primary key
#  nome_contato      :string(255)
#  nome_empressa     :string(255)
#  telefone_empressa :string(255)
#  telefone_celular  :string(255)
#  endereco          :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Prospect < ActiveRecord::Base
  attr_accessible :endereco, :nome_contato, :nome_empressa, :telefone_celular, :telefone_empressa

  validates :endereco,          presence: true
  validates :nome_contato,      presence: true
  validates :nome_empressa,     presence: true
  validates :telefone_celular,  presence: true
  validates :telefone_empressa, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
 
  validates :name,  presence: true, 
                    length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password,  presence: true,
                        length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authorize_user

  def home
    @title = '' 
    @prospects_cnt = Prospect.count
    @agents_cnt = 0
  end

  def prospects
    @title = 'Prospects'
  end

  def agents
    @title = 'Agents'  
  end

  def backoffice
    @title = 'Backoffice'  
  end

  private
    def authorize_user
      redirect_to login_url, notice: 'Accesso restrito' unless logged_in?
    end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_filter :authorize_user
  respond_to :json
  respond_to :html

  # GET /prospects
  # GET /prospects.json
  def index
    @prospects = Prospect.all

    respond_with @prospects
  end

  # GET /prospects/1
  # GET /prospects/1.json
  def show
    @prospect = Prospect.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prospect }
    end
  end

  # GET /prospects/new
  # GET /prospects/new.json
  def new
    @prospect = Prospect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prospect }
    end
  end

  # GET /prospects/1/edit
  def edit
    @prospect = Prospect.find(params[:id])
  end

  # POST /prospects
  # POST /prospects.json
  def create
    @prospect = Prospect.new(params[:prospect])

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to @prospect, notice: 'Prospect was successfully created.' }
        format.json { render json: @prospect, status: :created, location: @prospect }
      else
        format.html { render action: "new" }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prospects/1
  # PUT /prospects/1.json
  def update
    @prospect = Prospect.find(params[:id])

    respond_to do |format|
      if @prospect.update_attributes(params[:prospect])
        format.html { redirect_to @prospect, notice: 'Prospect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1
  # DELETE /prospects/1.json
  def destroy
    @prospect = Prospect.find(params[:id])
    @prospect.destroy

    respond_to do |format|
      format.html { redirect_to prospects_url }
      format.json { head :no_content }
    end
  end

  private
    def authorize_user
      redirect_to login_url, notice: 'Accesso restrito' unless logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = 'Login'
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login user
      redirect_to home_path
    else
      flash.now[:error] = 'email ou password est&aacute; invalida' # Not quite right!
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = 'Verkko CRM'

    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def flash_handler
    div = ""
    flash.each do |key, value|
      div += "<div class='container'>"
      div += "<div class='alert alert-#{key}' data-dismiss='alert'>"
      div += "<strong>#{value}</strong>"
      div += "</div></div>"
    end
    div
  end

  def error_class(model, sym)
    if model.errors.messages.has_key?(sym)
      "error"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def active_controller(cntrl_name)
    if cntrl_name == controller.controller_name
      return 'active'
    end
  end

  def active(cntrl_name)
    if cntrl_name == controller.controller_name + '#' + controller.action_name then
      return 'active'
    end
  end
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    self.current_user = nil  
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = title
    = stylesheet_link_tag "application", media: 'all'
    = javascript_include_tag "application"
    = favicon_link_tag
    = csrf_meta_tags
    -# put google analytics js and all thirdparty js at end of body
  %body
    = yield
= debug(params) if Rails.env.development?
-#= debug(Rails.env)

app/views/pages/_site_menu.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner{:data => {'scollspy' => 'scollspy'}}
    .container
      = link_to image_tag('verkko_logo_menubar.png', :class => 'logotipo') + ' Verkko CRM', home_url, :class => 'brand'
      %ul.nav
        %li{:class => active_controller('prospects')}
          = link_to 'Prospects Corban', '/prospects/#prospects'
        %li{:class => active('pages#agents')}
          = link_to 'Agents Corban', agents_url
        %li{:class => active('pages#backoffice')}
          = link_to 'Backoffice', backoffice_url
      %ul.nav.pull-right
        - if logged_in?
          %li{class:'dropdown', id:'fat-menu'}
            %a{ href:'#', class:'dropdown-toggle', data: {toggle: 'dropdown'}} Conta
            %ul.dropdown-menu
              %li
                = link_to raw('<i class=''icon-cog''></i> Configura&ccedil;&atilde;o'), '#'
              %li.divider
              %li
                = link_to raw('<i class=''icon-off''></i> Logout ') + current_user.name, logout_url, :method => :delete
        - else
          = link_to 'Login', login_url
.navbar-spacer
!= flash_handler

app/views/pages/agents.html.haml
= render 'site_menu'
.container
  %h1 Agents Corban
  #prospect_index
    %h2 Prospect Rendering Erro Fixed!

app/views/pages/backoffice.html.haml
= render 'site_menu'
.container
  %h1 Backoffice

app/views/pages/home.html.haml
= render 'site_menu'
.container
  %p
    %center
      = jqplot 350, 900, [[[0, 59], [1, 48], [2, 57], [3, 45], [4, 37], [5, 48], [6, 52], [7, 58], [8, 69], [9, 31], [10, 36], [11, 23], [12, 32], [13, 20], [14, 67], [15, 68], [16, 52], [17, 47], [18, 60], [19, 89]]]
  .row
    .span6
      %center
        %h3
          Numero de Prospects Ativo:
          = @prospects_cnt
        #pie_chart_prospects
        :javascript
          $(document).ready(function(){
              var plot1 = $.jqplot('pie_chart_prospects', [[['a',25],['b',14],['c',7]]], {
                grid: {
                  drawBorder: false,
                  drawGridlines: false,
                  background: '#f5f5f5',
                  shadow: false
                },
                seriesDefaults:{
                  renderer:$.jqplot.PieRenderer,
                  rendererOptions: {
                    showDataLabels: false }
                }
              });
          });
    .span6
      %center
        %h3
          Numero de Agents Ativo:
          = @agents_cnt
        #pie_chart_agents
        :javascript
          $(document).ready(function(){
            var plot1 = $.jqplot('pie_chart_agents', [[['a',75],['b',10],['c',10],['d',5]]], {
                grid: {
                  drawBorder: false,
                  drawGridlines: false,
                  background: '#f5f5f5',
                  shadow: false
                },
                seriesDefaults:{
                  renderer:$.jqplot.PieRenderer,
                  rendererOptions: {
                    showDataLabels: false }
                }
              });
          });

app/views/pages/prospects.html.haml
= render 'pages/site_menu'
.container
  %h1 Prospects Corban
  #prospect_index

app/views/prospects/_form.html.haml
= form_for @prospect do |f|
  - if @prospect.errors.any?
    #error_explanation
      %h3= "Tem #{pluralize(@prospect.errors.count, "erro")} na pagina:"
      %ul
        - @prospect.errors.full_messages.each do |msg|
          %li= msg

  .fieldset
    .control-group{:class => error_class(@prospect, :nome_contato)}
      .field
        = f.label :nome_contato
        = f.text_field :nome_contato
    .control-group{:class => error_class(@prospect, :nome_empressa)}
      .field
        = f.label :nome_empressa
        = f.text_field :nome_empressa
    .control-group{:class => error_class(@prospect, :telefone_empressa)}
      .field
        = f.label :telefone_empressa
        = f.text_field :telefone_empressa
    .control-group{:class => error_class(@prospect, :telefone_celular)}
      .field
        = f.label :telefone_celular
        = f.text_field :telefone_celular
    .control-group{:class => error_class(@prospect, :endereco)}
      .field
        = f.label :endereco
        = f.text_field :endereco
    .actions
      = button_tag "Salvar", :class => 'btn', 'data-disable-with' => "Processando ..."

app/views/prospects/edit.html.haml
= render 'pages/site_menu'
.container
  %h1 Prospect Corban

  = render 'form'

  = link_to 'Mostar', @prospect
  \|
  = link_to 'Voltar', prospects_path

app/views/prospects/index.html.haml
= render 'pages/site_menu'
.container
  %h1 Prospects Corban
  #prospect_index

  -#%table.table.table-bordered.table-striped
    %tr
      %th Nome contato
      %th Nome empressa
      %th Telefone empressa
      %th Telefone celular
      %th Endereco
      %th
      %th
      %th

    - @prospects.each do |prospect|
      %tr
        %td= prospect.nome_contato
        %td= prospect.nome_empressa
        %td= prospect.telefone_empressa
        %td= prospect.telefone_celular
        %td= prospect.endereco
        %td= link_to 'Mostrar', prospect
        %td= link_to 'Editar', edit_prospect_path(prospect)
        %td= link_to 'Apagar', prospect, :method => :delete, :data => { :confirm => 'Tem certeza?' }

  %br

  = link_to 'Novo Prospect', new_prospect_path

app/views/prospects/new.html.haml
= render 'pages/site_menu'
.container
  %h1 New prospect Corban

  = render 'form'

  = link_to 'Voltar', prospects_path

app/views/prospects/show.html.haml
= render 'pages/site_menu'
.container
  %p#notice= notice

  %p
    %b Nome contato:
    = @prospect.nome_contato
  %p
    %b Nome empressa:
    = @prospect.nome_empressa
  %p
    %b Telefone empressa:
    = @prospect.telefone_empressa
  %p
    %b Telefone celular:
    = @prospect.telefone_celular
  %p
    %b Endereco:
    = @prospect.endereco

  = link_to 'Editar', edit_prospect_path(@prospect)
  \|
  = link_to 'Voltar', prospects_path

app/views/users/new.html.haml
%h1 Sign Up
%p Find me in app/views/users/new.html.haml